#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
配置模块

包含所有的配置和Prompt模板
"""

from .prompts import (
    JUDGE_SYSTEM_PROMPT,
    JUDGE_SYSTEM_PROMPT_COT,
    COMMON_ATTACK_REQUIREMENTS,
    ATTACK_T12_INTERMEDIATE_SIGNAL_PROMPT_TEMPLATE,
    ATTACK_T19_DEAD_CODE_PROMPT_TEMPLATE,
    ATTACK_T20_COMMENT_PROMPT_TEMPLATE,
    ATTACK_T31_SIMPLE_INTERMEDIATE_PROMPT_TEMPLATE,
    ATTACK_T34_RENAME_PROMPT_TEMPLATE,
    LLM_PARAM_RULES,
    format_attack_prompt,
)

__all__ = [
    'JUDGE_SYSTEM_PROMPT',
    'JUDGE_SYSTEM_PROMPT_COT',
    'COMMON_ATTACK_REQUIREMENTS',
    'ATTACK_T12_INTERMEDIATE_SIGNAL_PROMPT_TEMPLATE',
    'ATTACK_T19_DEAD_CODE_PROMPT_TEMPLATE',
    'ATTACK_T20_COMMENT_PROMPT_TEMPLATE',
    'ATTACK_T31_SIMPLE_INTERMEDIATE_PROMPT_TEMPLATE',
    'ATTACK_T34_RENAME_PROMPT_TEMPLATE',
    'LLM_PARAM_RULES',
    'format_attack_prompt',
]
