#!/bin/bash
# vLLM手动安装指南
# 请逐条复制粘贴执行，观察是否有错误

echo "========================================="
echo " vLLM环境安装 - 分步执行"
echo "========================================="
echo ""
echo "Step 1: 激活vllm_deploy环境"
echo "  conda activate vllm_deploy"
echo ""
echo "Step 2: 安装PyTorch for CUDA 12.8 (约2-3分钟)"
echo "  pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128"
echo ""
echo "Step 3: 安装vLLM (约5-10分钟)"
echo "  pip install vllm"
echo ""
echo "Step 4: 安装额外依赖"
echo "  pip install transformers accelerate"
echo ""
echo "Step 5: 测试安装"
echo "  python -c \"import vllm; print('✓ vLLM:', vllm.__version__)\""
echo "  python -c \"import torch; print('✓ PyTorch:', torch.__version__, 'CUDA:', torch.cuda.is_available())\""
echo ""
echo "========================================="
echo " 使用方法"
echo "========================================="
echo ""
echo "启动攻击模型："
echo "  conda activate vllm_deploy"
echo "  CUDA_VISIBLE_DEVICES=0,1 python -m vllm.entrypoints.openai.api_server \\"
echo "    --model /data3/pengqingsong/LLM_attack/saves/obfuscation_lora_merged \\"
echo "    --port 8002 --tensor-parallel-size 2"
echo ""
echo "启动判断模型："
echo "  conda activate vllm_deploy"
echo "  CUDA_VISIBLE_DEVICES=2,3 python -m vllm.entrypoints.openai.api_server \\"
echo "    --model /data3/pengqingsong/Model/Qwen2.5-Coder-7B \\"
echo "    --port 8001 --tensor-parallel-size 2"
echo ""
