### Model
model_name_or_path: /mnt/public/pqs/Model/Qwen2.5-Coder-7B/
adapter_name_or_path: /mnt/public/pqs/Veri_atack/project_up/saves/attack_lora_v1
template: qwen
finetuning_type: lora

### Export
export_dir: /mnt/public/pqs/Veri_atack/project_up/saves/attack_lora_merged
export_size: 2
export_device: auto
export_legacy_format: false
